pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    // This will fail if hello.cpp has a compilation error
                    sh 'g++ hello.cpp -o hello_exec'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    // Run the executable and force failure if it exits with an error
                    sh './hello_exec || exit 1'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    // Force the deploy stage to fail
                    sh 'exit 1'
                }
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed at some stage!'
        }
    }
}
