pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    // This will fail due to the syntax error in hello.cpp
                    sh 'g++ hello.cpp -o PES2UG22CS909'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    // This will fail if the build didn't generate the executable
                    sh './PES2UG22CS909'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    // Force the Deploy stage to fail manually
                    sh 'exit 1'
                }
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed'
        }
    }
}



